version: '3.8'

services:
  app:
    build: .
    container_name: social-scraper
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/social_scraper
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
